version: "8.0.0.{build}"

platform: Any CPU
configuration: Release
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019

cache:
  # Note: this must match the $rabbitmq_installer_path and $erlang_installer_path values in
  # tools\appveyor\install.ps1
  - "%HOMEDRIVE%%HOMEPATH%\\rabbitmq-server-3.8.9.exe"
  - "%HOMEDRIVE%%HOMEPATH%\\otp_win64_23.1.2.exe"

install:
  - ps: .\tools\appveyor\install.ps1

build_script: 
  - cmd: .\build.bat

test_script:
  - cmd: .\run-test.bat

nuget:
  disable_publish_on_pr: true
